### ISSUE TITLE
Use AngularJS for all views?

### ISSUE THREAD

**Issue by jefffohl** [rhyolight/smartthings.htm.bridge#15]
It might make things easier to develop, and faster to render, if we used Angular for all views. Angular can handle templates, routing, and manage all the AJAX calls we want to make. Also, there are a lot of tools for making unit tests and end-to-end tests built into Angular, which makes it a good choice for Single Page App development.

We will also have a nice separation of concerns. Angular will handle the UI client, and Python can act as the proxy server between the various services.

@rhyolight do you have any objections? I know that you haven't used Angular before, so I don't want to force you into a framework you are not familiar with, and therefore hamstring your development process. There is admittedly a learning curve in working with Angular, but I am happy to act as a guide, and write tutorials if needed.

**Comment by rhyolight** [comment]
:+1:

**Comment by rhyolight** [comment]
I'm going to let you take over the frontend if you're willing. Please do whatever you think is appropriate.
