### ISSUE TITLE
Add metadata of periodicity to _sensors response?

### ISSUE THREAD

**Issue by jefffohl** [rhyolight/smartthings.htm.bridge#2]
I was trying to think of ways to dynamically update graph data from the bridge. It occurred to me that each sensor might have a different periodicity (that is, how often it pushes data out to the bridge). This information could be passed along with the `_sensors` request, allowing the charting client to know how often to request new data.

**Comment by rhyolight** [comment]
You are right, but at this stage I think we can just update the client every 30 seconds or something. I don't need this prototype to be really really live. :)
